### ISSUE TITLE
Remember to add e routes in your router

### ISSUE THREAD

**Issue by ygongdev** [CristobalMe/Event_Finder#2]
https://github.com/CristobalMe/Event_Finder/blob/7b3a109135a2adf376f6420f0c29230c89317396/frontend/src/App.jsx#L15

I saw that in your header's navbar, you're already using <LinkTo> for some routes, make sure these links work by adding the necessary routes in your router config.

**Comment by CristobalMe** [comment]
Done.
Thank you
